Repository DPuddinu/agenda-tutorato-react, pull requests merged in 2024-08, with the labels that each got.

#7 Feature API managment
  src/App.tsx
  src/core/api.ts
Labels: features

#8 CHORE: dependencies and basic routing
  package-lock.json
  package.json
  src/App.tsx
  src/components/protected-page.tsx
  src/components/providers/AuthProvider.tsx
  src/core/api.ts
  src/features/auth/types/auth.types.ts
  src/hooks/useAuth.tsx
  src/main.tsx
  src/pages/appointments-page.tsx
  src/pages/landing-page.tsx
  src/pages/login-page.tsx
  src/routes/routes.tsx
Labels: chore

#12 FEATURE login api
  src/core/api.ts
  src/features/auth/api/auth.ts
Labels: features

#14 FEATURE register api
  src/features/auth/api/auth.ts
Labels: chore, features

#20 FEATURE: login control
  src/pages/login/login-page.tsx
  src/pages/login/login.css
  src/styles/common.css
Labels: features

#23 TEST: add cypress and create a test
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  tsconfig.app.json
  tsconfig.json
Labels: test

#24 FEATURE: register control
  src/features/auth/types/auth.types.ts
  src/pages/register/register-page.tsx
  src/routes/routes.tsx
Labels: features

#26 FIX: register and login error
  src/features/auth/types/auth.types.ts
  src/pages/login/login-page.tsx
  src/pages/register/register-page.tsx
Labels: bug

#29 TEST: register cypress test
  .eslintrc.cjs
  .prettierrc.json
  README.md
  cypress.config.ts
  cypress/contants.ts
  cypress/e2e/user_login.cy.ts
  cypress/e2e/user_register.cy.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/protected-page.tsx
  src/components/providers/AuthProvider.tsx
  src/core/api.ts
  src/features/auth/api/auth.ts
  src/features/auth/types/auth.types.ts
  src/hooks/useAuth.tsx
  src/main.tsx
  src/pages/appointments-page.tsx
  src/pages/landing-page.tsx
  src/pages/login/login-page.tsx
  src/pages/login/login.css
  src/pages/register/register-page.tsx
  src/routes/routes.tsx
  src/styles/common.css
  tsconfig.app.json
  vite.config.ts
Labels: test

#30 STYLE: add space error message
  src/pages/login/login-page.tsx
  src/styles/common.css
Labels: style

#32 FEATURE: landing page
  .prettierrc.json
  src/assets/placeholder.svg
  src/pages/appointments/appointments-page.tsx
  src/pages/home/home.tsx
  src/pages/landing-page.tsx
  src/pages/landingPage/landing-page.tsx
  src/pages/landingPage/landing.css
  src/pages/login/login-page.tsx
  src/pages/register/register-page.tsx
  src/routes/routes.tsx
  src/styles/common.css
Labels: features, style

#31 TEST: login form
  cypress/e2e/user_login.cy.ts
  src/pages/login/login-page.tsx
Labels: test

#34 FEATURE: Appointment form
  src/components/appointment-form.tsx
  src/components/appointmentForm.css
  src/pages/landingPage/landing.css
  src/routes/routes.tsx
  src/styles/common.css
Labels: features
